module BlindfoldChessTest.BlindfoldChessMechanics.Notation.CodecTest

open BlindfoldChessMechanics
open FSharpx.Collections
open NUnit.Framework

let endgamePuzzlesLevel1Jsonl =
    [ """{"MetaTags":{"category_id":"0","index_in_level":"0","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":2,"Item2":5},"ToCoords":{"Item1":1,"Item2":6},"IsCapture":true,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"1","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":6,"Item2":3},"ToCoords":{"Item1":5,"Item2":5},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"2","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":4,"Item2":2},"ToCoords":{"Item1":2,"Item2":3},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"3","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":2,"Item2":4},"ToCoords":{"Item1":3,"Item2":4},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"4","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":2,"Item2":3},"ToCoords":{"Item1":1,"Item2":2},"IsCapture":true,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"5","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":7,"Item2":6},"ToCoords":{"Item1":2,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"6","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]}],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]}]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":2},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":7,"Item2":7},"ToCoords":{"Item1":7,"Item2":5},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"7","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]}],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":7,"Item2":6},"ToCoords":{"Item1":1,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"8","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]}],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":2},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":0,"Item2":6},"ToCoords":{"Item1":0,"Item2":5},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"9","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]}],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":5,"Item2":4},"ToCoords":{"Item1":3,"Item2":3},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"10","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]}],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Bishop"},"FromCoords":{"Item1":4,"Item2":7},"ToCoords":{"Item1":3,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"11","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":5,"Item2":2},"ToCoords":{"Item1":3,"Item2":3},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"12","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":true}]},null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]}],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Pawn"},"FromCoords":{"Item1":1,"Item2":7},"ToCoords":{"Item1":0,"Item2":7},"IsCapture":false,"Promotion":{"Case":"Some","Fields":[{"Case":"Queen"}]},"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[{"Item1":1,"Item2":7},{"Item1":1,"Item2":7},{"Item1":1,"Item2":7}]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"13","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":3,"Item2":4},"ToCoords":{"Item1":5,"Item2":3},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"14","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":false}]},null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":true}]},null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Bishop"},"FromCoords":{"Item1":3,"Item2":3},"ToCoords":{"Item1":4,"Item2":4},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"15","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]}],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":2},"Moves":[{"Piece":{"Case":"Pawn"},"FromCoords":{"Item1":5,"Item2":5},"ToCoords":{"Item1":6,"Item2":5},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"16","level":"0"},"InitialPosition":{"Board":[[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":false}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":2,"Item2":4},"ToCoords":{"Item1":0,"Item2":4},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":true,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"17","level":"0"},"InitialPosition":{"Board":[[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":false}]},null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Bishop"},"FromCoords":{"Item1":0,"Item2":3},"ToCoords":{"Item1":1,"Item2":4},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"18","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]}]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":4,"Item2":3},"ToCoords":{"Item1":4,"Item2":7},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":true,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"19","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":true}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":5,"Item2":4},"ToCoords":{"Item1":7,"Item2":5},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"20","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":2},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":0,"Item2":7},"ToCoords":{"Item1":4,"Item2":7},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"21","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]}],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":4,"Item2":5},"ToCoords":{"Item1":5,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"22","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]}],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":3,"Item2":4},"ToCoords":{"Item1":5,"Item2":5},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"23","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]}],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":1,"Item2":4},"ToCoords":{"Item1":2,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"24","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]}],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Bishop"},"FromCoords":{"Item1":3,"Item2":2},"ToCoords":{"Item1":4,"Item2":1},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"25","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":false}]},null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":true}]},null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Queen"},"FromCoords":{"Item1":7,"Item2":2},"ToCoords":{"Item1":6,"Item2":2},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"26","level":"0"},"InitialPosition":{"Board":[[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":false}]},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":true}]}]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Queen"},"FromCoords":{"Item1":0,"Item2":2},"ToCoords":{"Item1":0,"Item2":7},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"27","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Bishop"},"FromCoords":{"Item1":1,"Item2":4},"ToCoords":{"Item1":4,"Item2":7},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"28","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":2,"Item2":0},"ToCoords":{"Item1":1,"Item2":0},"IsCapture":true,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"29","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":true}]},null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":false}]},null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Queen"},"FromCoords":{"Item1":5,"Item2":4},"ToCoords":{"Item1":6,"Item2":3},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"30","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null,null,null],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":7,"Item2":1},"ToCoords":{"Item1":6,"Item2":0},"IsCapture":true,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"31","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":3,"Item2":6},"ToCoords":{"Item1":5,"Item2":6},"IsCapture":true,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"32","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]}],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":2,"Item2":4},"ToCoords":{"Item1":4,"Item2":5},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"33","level":"0"},"InitialPosition":{"Board":[[{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":false}]},null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":true}]},null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Queen"},"FromCoords":{"Item1":0,"Item2":0},"ToCoords":{"Item1":1,"Item2":0},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"34","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]}],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":3,"Item2":6},"ToCoords":{"Item1":2,"Item2":6},"IsCapture":true,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"35","level":"0"},"InitialPosition":{"Board":[[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":7,"Item2":2},"ToCoords":{"Item1":7,"Item2":1},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"36","level":"0"},"InitialPosition":{"Board":[[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":1,"Item2":6},"ToCoords":{"Item1":0,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":true,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"37","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":2},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":3,"Item2":4},"ToCoords":{"Item1":6,"Item2":4},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"38","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":7,"Item2":0},"ToCoords":{"Item1":3,"Item2":0},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"39","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":true}]}],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]}],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Queen"},"FromCoords":{"Item1":1,"Item2":5},"ToCoords":{"Item1":3,"Item2":7},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"40","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":6,"Item2":4},"ToCoords":{"Item1":5,"Item2":3},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"41","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":false}]},null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Queen"},"FromCoords":{"Item1":5,"Item2":6},"ToCoords":{"Item1":7,"Item2":4},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"42","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Bishop"},"FromCoords":{"Item1":2,"Item2":2},"ToCoords":{"Item1":4,"Item2":0},"IsCapture":true,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"43","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]}],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]}],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":4,"Item2":6},"ToCoords":{"Item1":3,"Item2":7},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"44","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":1},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":6,"Item2":5},"ToCoords":{"Item1":6,"Item2":4},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"45","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":true}]},null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"King"},"FromCoords":{"Item1":2,"Item2":6},"ToCoords":{"Item1":1,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":false,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"46","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]}],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Knight"},"FromCoords":{"Item1":4,"Item2":5},"ToCoords":{"Item1":6,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"47","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]}],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null],[null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Queen"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":false,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":1},"Moves":[{"Piece":{"Case":"Queen"},"FromCoords":{"Item1":2,"Item2":6},"ToCoords":{"Item1":4,"Item2":6},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"48","level":"0"},"InitialPosition":{"Board":[[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]},null,null,null,null,null,null],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},{"Case":"Some","Fields":[{"PieceType":{"Case":"Bishop"},"IsWhite":true}]}],[null,null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Knight"},"IsWhite":false}]}],[null,null,null,null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":1,"FullMove":2},"Moves":[{"Piece":{"Case":"Bishop"},"FromCoords":{"Item1":2,"Item2":1},"ToCoords":{"Item1":1,"Item2":2},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}"""
      """{"MetaTags":{"category_id":"0","index_in_level":"49","level":"0"},"InitialPosition":{"Board":[[null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":false}]},null,{"Case":"Some","Fields":[{"PieceType":{"Case":"King"},"IsWhite":true}]},null,null,null,null],[null,null,null,null,null,null,null,null],[{"Case":"Some","Fields":[{"PieceType":{"Case":"Pawn"},"IsWhite":false}]},null,null,null,null,null,null,null],[null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":false}]},null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,{"Case":"Some","Fields":[{"PieceType":{"Case":"Rook"},"IsWhite":true}]},null,null,null,null]],"IsWhiteToMove":true,"Castling":{"WhiteKingSideCastle":false,"WhiteQueenSideCastle":false,"BlackKingSideCastle":false,"BlackQueenSideCastle":false},"EnPassant":null,"HalfMove":0,"FullMove":2},"Moves":[{"Piece":{"Case":"Rook"},"FromCoords":{"Item1":7,"Item2":3},"ToCoords":{"Item1":7,"Item2":1},"IsCapture":false,"Promotion":null,"IsCheck":true,"IsMate":false,"IsStalemate":false,"SamePieceCoords":[]}],"Result":null}""" ]

let exp =
    [ """{"IsWhiteToMove":false,"WhitePieces":["♔d3","♙a4","♖g2"],"BlackPieces":["♚f3","♟︎f4"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔d5","♗f4","♗h5"],"BlackPieces":["♚d8","♞d7"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔e5","♗f2","♗f3"],"BlackPieces":["♚b5","♞c5"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔g5","♙f3","♖e3"],"BlackPieces":["♚d4","♜a4"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔e6","♙b4","♖c2"],"BlackPieces":["♚d3","♟︎b5"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔g2","♖g8"],"BlackPieces":["♚e3","♟︎e4","♜a3"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔g2","♙h5","♖h8"],"BlackPieces":["♚f6","♜f4"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔h1","♖g8"],"BlackPieces":["♚f2","♟︎f4","♜a2"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔g1","♙a7"],"BlackPieces":["♚g3","♟︎f2","♟︎h3"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔f5","♗c2","♗h4"],"BlackPieces":["♚f7","♞e6"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔d5","♗d2","♗h5"],"BlackPieces":["♚d7","♞e6"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔b5","♗f3","♗g5"],"BlackPieces":["♚c8","♞c6"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔g3","♘f1","♖a8"],"BlackPieces":["♚g5","♟︎h2"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔f7","♖e8"],"BlackPieces":["♚f3","♞e4","♜g1"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔h2","♘d6"],"BlackPieces":["♚c2","♟︎c4","♝d4"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔e4","♙h3","♙f6"],"BlackPieces":["♚b2","♜g3"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔d1","♖c2"],"BlackPieces":["♚e4","♝c3","♜e3"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔a6","♙b5","♗b7"],"BlackPieces":["♚g5","♝d1"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔h8","♖g8"],"BlackPieces":["♚f6","♞f3","♜d5"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔g6","♙h7","♘f7"],"BlackPieces":["♚f4","♞e6"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔d3","♖h1"],"BlackPieces":["♚c5","♟︎b4","♜c4"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔f5","♙a5","♖a7"],"BlackPieces":["♚g8","♜h5"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔h7","♖e8"],"BlackPieces":["♚f3","♞e4","♜g1"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔h5","♖a5"],"BlackPieces":["♚f6","♞e2","♜f4"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔e5","♗c4","♗h4"],"BlackPieces":["♚d7","♞e8"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔b8","♙b7","♕c8"],"BlackPieces":["♚g3","♛d6"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔h5","♖a5","♕h8"],"BlackPieces":["♚b3","♛c1"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔e5","♗e2","♗b4"],"BlackPieces":["♚f7","♞e8"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔d5","♖a3"],"BlackPieces":["♚c2","♟︎a2","♟︎b2"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔e7","♙f5","♕e6"],"BlackPieces":["♚d2","♛b7"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔b8","♙a6"],"BlackPieces":["♚c6","♟︎a7","♞c4"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔g7","♙g6","♖f8"],"BlackPieces":["♚e7","♜g4"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔d3","♙c7","♘e3"],"BlackPieces":["♚h4","♞d6"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔e6","♖h6","♕g8"],"BlackPieces":["♚b2","♛a1"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔h5","♙g3","♖h6"],"BlackPieces":["♚a4","♜g4"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔a6","♙b7","♖b1"],"BlackPieces":["♚c8","♜d7"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔d1","♙g4","♖c5"],"BlackPieces":["♚d3","♜g2"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔f5","♙g5","♖e4"],"BlackPieces":["♚f7","♜g6"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔d4","♙c5","♖e4"],"BlackPieces":["♚f6","♜a8"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔e7","♕h1"],"BlackPieces":["♚h5","♟︎g6","♛f2"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔f5","♗b3","♗b4"],"BlackPieces":["♚e7","♞c5"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔f8","♙h6","♕g6"],"BlackPieces":["♚b5","♛c8"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔a4","♗c3"],"BlackPieces":["♚e4","♟︎a5","♜c5"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔f3","♙h2","♙g4"],"BlackPieces":["♚g5","♟︎h3"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔c7","♙d7","♖b7"],"BlackPieces":["♚f7","♜a8"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔e1","♙d3","♙a4"],"BlackPieces":["♚g3","♟︎f4"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔h5","♖e8"],"BlackPieces":["♚f3","♞f5","♜g1"]}"""
      """{"IsWhiteToMove":false,"WhitePieces":["♔d5","♕f6"],"BlackPieces":["♚h4","♟︎g6","♛g3"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔g4","♗b3","♗h4"],"BlackPieces":["♚g6","♞h5"]}"""
      """{"IsWhiteToMove":true,"WhitePieces":["♔d1","♖d8"],"BlackPieces":["♚b1","♟︎a3","♜c4"]}""" ]

type EndgamePuzzle =
    { IsWhiteToMove: bool
      WhitePieces: string list
      BlackPieces: string list }

[<Test>]
let ``Description of endgame puzzles in level 1`` () =
    let act =
        List.map
            (fun jsonStr ->
                let parsedGame = Notation.Parser.jsonOfGame jsonStr
                let initPos = parsedGame.InitialPosition
                let whitePieces, blackPieces = Notation.Emitter.textsOfPieces true initPos.Board
                let whitePiecesList = LazyList.toList whitePieces
                let blackPiecesList = LazyList.toList blackPieces

                { IsWhiteToMove = initPos.IsWhiteToMove
                  WhitePieces = whitePiecesList
                  BlackPieces = blackPiecesList }
                |> Newtonsoft.Json.JsonConvert.SerializeObject)
            endgamePuzzlesLevel1Jsonl

    Assert.AreEqual(exp, act)
